# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayreport_app', '0002_remove_calevent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='id',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
