# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dayreport_app', '0003_auto_20180107_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
