# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayreport_app', '0005_auto_20180108_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='start',
            field=models.DateField(),
        ),
    ]
