# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 01:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('code_num', models.CharField(max_length=512)),
                ('code_color', models.CharField(blank=True, max_length=512, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('className', models.CharField(blank=True, max_length=512, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_writername', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
