# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='code_num',
            new_name='code_id',
        ),
    ]
