# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0002_auto_20180210_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
