# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 01:51
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0003_auto_20180210_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
