# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0004_auto_20180210_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
    ]
