# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_time_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_time',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='day_time',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
