# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_time_app', '0002_auto_20180221_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_time',
            name='detail',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
    ]
