# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_time_app', '0003_day_time_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_time',
            name='detail',
            field=models.TextField(blank=True, max_length=5120, null=True),
        ),
    ]
